services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install aiohttp aiogram aiosqlite Babel magic-filter
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
